// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var message = "Hello, there!";

var text = "that`s me again";

console.log(message);

console.log();

console.log(text);

var x = 1234567;

exports.message = message;
exports.x = x;
exports.text = text;
/*  Not a pure module */
