// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var sum = 15.5 + 30.1;

var diff = 15.5 - 30.1;

var sqrt = Math.sqrt(sum);

console.log("\n    Sum is " + String(sum) + ",\n    Difference is " + String(diff) + ",\n    Square sum's root is " + String(sqrt));

var a = 15.5;

var b = 30.1;

exports.a = a;
exports.b = b;
exports.sum = sum;
exports.diff = diff;
exports.sqrt = sqrt;
/* sqrt Not a pure module */
