// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var add = 13;

var minus = -3;

var mult = 5.0 * 8.0;

var div = 5.0 / 8.0;

console.log("The result of summary is " + String(add) + ", the subtractions is " + String(minus));

console.log("The multiplication is " + String(mult) + " and division is " + String(div));

var x = 5.0;

var y = 8.0;

exports.x = x;
exports.y = y;
exports.add = add;
exports.minus = minus;
exports.mult = mult;
exports.div = div;
/*  Not a pure module */
