// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var moon_weight = String(0.17 * 85.0);

console.log("The weight on the Moon is about " + moon_weight);

var $$const = 0.17;

var earths_weight = 85.0;

exports.$$const = $$const;
exports.earths_weight = earths_weight;
exports.moon_weight = moon_weight;
/* moon_weight Not a pure module */
