// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var sum = 21;

var square = Math.sqrt(Math.imul(Math.imul(Math.imul(sum, sum - 9 | 0), sum - 6 | 0), sum - 6 | 0));

console.log("The area of triangle is = " + String(sum));

var a = 9;

var b = 6;

var c = 6;

exports.a = a;
exports.b = b;
exports.c = c;
exports.sum = sum;
exports.square = square;
/* square Not a pure module */
